[package]
name = "bevy_save"
version = "0.3.2"
edition = "2021"
description = "A framework for saving and loading game state in Bevy."
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/hankjordan/bevy_save"

[dev-dependencies]
bevy = { version = "0.9" }

[dependencies]
bevy = { version = "0.9", default-features = false, features = ["bevy_scene"] }
rmp-serde = "1.1"
serde = { version = "1.0" }
platform-dirs = "0.3"
lazy_static = "1.4"
