[package]
name = "bevy_save"
version = "0.5.0"
edition = "2021"
description = "A framework for saving and loading game state in Bevy."
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/hankjordan/bevy_save"

[dev-dependencies]
bevy = { version = "0.10" }
bevy-inspector-egui = "0.18"
serde_json = "1.0"

[dependencies]
bevy = { version = "0.10", default-features = false }
rmp-serde = "1.1"
serde = { version = "1.0" }
platform-dirs = "0.3"
lazy_static = "1.4"
thiserror = "1.0"
