[workspace]
members = [".", "erased-serde"]

[package]
name = "bevy_save"
version = "0.7.0"
edition = "2021"
description = "A framework for saving and loading game state in Bevy."
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/hankjordan/bevy_save"

[dev-dependencies]
bevy = { version = "0.10" }
bevy-inspector-egui = "0.18"
serde_json = "1.0"

[features]
default = ["bevy_asset", "bevy_render", "bevy_sprite"]
bevy_asset = ["bevy/bevy_asset"]
bevy_render = ["bevy/bevy_render"]
bevy_sprite = ["bevy/bevy_sprite"]

[dependencies]
bevy_save-erased-serde = { path = "erased-serde", version = "0.4.0" }
bevy = { version = "0.10", default-features = false }
rmp-serde = "1.1"
serde = { version = "1.0" }
platform-dirs = "0.3"
lazy_static = "1.4"
thiserror = "1.0"
